### ISSUE TITLE
Impossible to save password in Browser after upgrade to 2.1.0.9

### ISSUE THREAD

**Issue by atlochowski** [sailfishos/sailfish-browser#559]
It's impossible to save and update password in Browser after update to 2.1.0.9

**Comment by atlochowski** [comment]
when I launch Browser from terminal I receiving output like this `
`[W] unknown:25 - file:///usr/lib/qt5/qml/Sailfish/WebView/Popups/PasswordManagerDialog.qml:25: TypeError: Property 'sendAsyncMessage' of object QQuickItem(0x53d20ab0) is not a function`
when I try to Save or Cancel. 
`

**Comment by rainemak** [comment]
Thanks for reporting. Will do my best to push a fix into the 2.1.1 release.
